const BoardFixture = [
  [{"row":0,"col":0,"value":3,"display":" ","mutable":true},
   {"row":0,"col":1,"value":5,"display":5,"mutable":false},
   {"row":0,"col":2,"value":8,"display":8,"mutable":false},
   {"row":0,"col":3,"value":7,"display":" ","mutable":true},
   {"row":0,"col":4,"value":2,"display":2,"mutable":false},
   {"row":0,"col":5,"value":9,"display":9,"mutable":false},
   {"row":0,"col":6,"value":4,"display":4,"mutable":false},
   {"row":0,"col":7,"value":6,"display":6,"mutable":false},
   {"row":0,"col":8,"value":1,"display":" ","mutable":true}],
  [{"row":1,"col":0,"value":7,"display":" ","mutable":true},
   {"row":1,"col":1,"value":6,"display":6,"mutable":false},
   {"row":1,"col":2,"value":4,"display":4,"mutable":false},
   {"row":1,"col":3,"value":3,"display":" ","mutable":true},
   {"row":1,"col":4,"value":8,"display":" ","mutable":true},
   {"row":1,"col":5,"value":1,"display":" ","mutable":true},
   {"row":1,"col":6,"value":2,"display":" ","mutable":true},
   {"row":1,"col":7,"value":9,"display":" ","mutable":true},
   {"row":1,"col":8,"value":5,"display":5,"mutable":false}],
  [{"row":2,"col":0,"value":1,"display":1,"mutable":false},
   {"row":2,"col":1,"value":2,"display":" ","mutable":true},
   {"row":2,"col":2,"value":9,"display":9,"mutable":false},
   {"row":2,"col":3,"value":5,"display":" ","mutable":true},
   {"row":2,"col":4,"value":4,"display":" ","mutable":true},
   {"row":2,"col":5,"value":6,"display":6,"mutable":false},
   {"row":2,"col":6,"value":8,"display":" ","mutable":true},
   {"row":2,"col":7,"value":3,"display":3,"mutable":false},
   {"row":2,"col":8,"value":7,"display":7,"mutable":false}],
  [{"row":3,"col":0,"value":6,"display":6,"mutable":false},
   {"row":3,"col":1,"value":3,"display":3,"mutable":false},
   {"row":3,"col":2,"value":7,"display":7,"mutable":false},
   {"row":3,"col":3,"value":9,"display":9,"mutable":false},
   {"row":3,"col":4,"value":4,"display":" ","mutable":true},
   {"row":3,"col":5,"value":2,"display":" ","mutable":true},
   {"row":3,"col":6,"value":1,"display":" ","mutable":true},
   {"row":3,"col":7,"value":8,"display":" ","mutable":true},
   {"row":3,"col":8,"value":5,"display":" ","mutable":true}],
  [{"row":4,"col":0,"value":4,"display":" ","mutable":true},
   {"row":4,"col":1,"value":2,"display":2,"mutable":false},
   {"row":4,"col":2,"value":8,"display":8,"mutable":false},
   {"row":4,"col":3,"value":5,"display":" ","mutable":true},
   {"row":4,"col":4,"value":1,"display":" ","mutable":true},
   {"row":4,"col":5,"value":7,"display":7,"mutable":false},
   {"row":4,"col":6,"value":6,"display":" ","mutable":true},
   {"row":4,"col":7,"value":3,"display":3,"mutable":false},
   {"row":4,"col":8,"value":9,"display":9,"mutable":false}],
  [{"row":5,"col":0,"value":9,"display":9,"mutable":false},
   {"row":5,"col":1,"value":5,"display":5,"mutable":false},
   {"row":5,"col":2,"value":1,"display":" ","mutable":true},
   {"row":5,"col":3,"value":6,"display":" ","mutable":true},
   {"row":5,"col":4,"value":8,"display":" ","mutable":true},
   {"row":5,"col":5,"value":3,"display":3,"mutable":false},
   {"row":5,"col":6,"value":2,"display":2,"mutable":false},
   {"row":5,"col":7,"value":7,"display":" ","mutable":true},
   {"row":5,"col":8,"value":4,"display":4,"mutable":false}],
  [{"row":6,"col":0,"value":2,"display":" ","mutable":true},
   {"row":6,"col":1,"value":1,"display":1,"mutable":false},
   {"row":6,"col":2,"value":6,"display":" ","mutable":true},
   {"row":6,"col":3,"value":5,"display":" ","mutable":true},
   {"row":6,"col":4,"value":9,"display":" ","mutable":true},
   {"row":6,"col":5,"value":3,"display":" ","mutable":true},
   {"row":6,"col":6,"value":8,"display":" ","mutable":true},
   {"row":6,"col":7,"value":7,"display":" ","mutable":true},
   {"row":6,"col":8,"value":4,"display":" ","mutable":true}],
  [{"row":7,"col":0,"value":8,"display":" ","mutable":true},
   {"row":7,"col":1,"value":4,"display":4,"mutable":false},
   {"row":7,"col":2,"value":3,"display":3,"mutable":false},
   {"row":7,"col":3,"value":1,"display":1,"mutable":false},
   {"row":7,"col":4,"value":7,"display":" ","mutable":true},
   {"row":7,"col":5,"value":2,"display":2,"mutable":false},
   {"row":7,"col":6,"value":9,"display":9,"mutable":false},
   {"row":7,"col":7,"value":5,"display":5,"mutable":false},
   {"row":7,"col":8,"value":6,"display":" ","mutable":true}],
  [{"row":8,"col":0,"value":7,"display":7,"mutable":false},
   {"row":8,"col":1,"value":9,"display":" ","mutable":true},
   {"row":8,"col":2,"value":5,"display":" ","mutable":true},
   {"row":8,"col":3,"value":4,"display":" ","mutable":true},
   {"row":8,"col":4,"value":6,"display":" ","mutable":true},
   {"row":8,"col":5,"value":8,"display":8,"mutable":false},
   {"row":8,"col":6,"value":3,"display":3,"mutable":false},
   {"row":8,"col":7,"value":1,"display":" ","mutable":true},
   {"row":8,"col":8,"value":2,"display":2,"mutable":false}]];
   
export default BoardFixture;   